### ISSUE TITLE
Streamline Thread Installation by Eliminating Model Rebuild

### ISSUE THREAD

**Issue by KadeMorton** [arachne-threat-intel/thread#93]
**Describe the bug**
Feedback indicates that the process of rebuilding machine learning models during the installation of Thread significantly extends the setup time. This step, inherited from our fork of TRAM, is not necessary as the models are covered under an open source license and contain no proprietary content. Removing this step from the installation process will drastically reduce the time required to get Thread operational on new installations.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Thread by following the instructions here https://github.com/arachne-threat-intel/thread/blob/main/README.md
2. You will see that as part of the installation, the ML models are rebuilt and this takes a significant amount of time.

**Expected behavior**
The installation being faster, facilitated by the ML models not being rebuilt each installation.

**Thread details (please complete the following information):**
- [config.yml](https://github.com/arachne-threat-intel/thread/blob/main/threadcomponents/conf/config.yml) changes
- Tagged-version used or output of `git rev-parse --short HEAD`

**Desktop (please complete the following information):**

**Additional context**

**Acceptance criteria**
- Modify the installation script for Thread to bypass the machine learning model rebuilding process.
- Ensure that pre-built, open source licensed models are included in the installation package and are correctly loaded during setup.
- Test the modified installation process to ensure that it works seamlessly and the models are correctly integrated without the rebuild step.
- Update the installation documentation to reflect the change in process, specifying the removal of the model rebuilding step and the inclusion of pre-built models.
- Conduct a time comparison test to document the time saved by removing this step.

**Milestones**
1. **Script Modification**: Complete modification of the installation scripts to remove the model rebuilding process.
3. **Integration Testing**: Test the installation process in various environments to ensure stability and functionality.
4. **Documentation Update**: Update the installation documentation post-testing to reflect the changes made.
5. **Deployment and Feedback Collection**: Roll out the updated installation process and collect user feedback to gauge impact and detect any unforeseen issues.

**Comment by jecarr** [comment]
Hi @KadeMorton

The linked PR had an updated models file. Submitting a report in my dev environment using that file did not trigger a rebuild.

We don't have any docs that need to be updated; we didn't state model-rebuilds were an installation step. These rebuilds happen because:

- Thread uses a dependency for the types of models
- This dependency was version x when Tram committed the models file
- When you set up a new environment, the dependency is most likely a major-version upgrade from x
- The models need to be rebuilt because of this version difference

Given your point about a docs-update, we could add in the installation steps a warning that this rebuild may happen. In the future, we should try to commit ready-to-use models given any dependency-version updates. 

As the PR is merged, this linked issue closed automatically but did you want it reopened given this, your acceptance criteria and milestone points may be outstanding (e.g. time comparison tests, user-feedback)?

**Comment by KadeMorton** [comment]
If it's just time comparison tests and user-feedback I think we can leave this closed. Just ensure that there is an update to the docs  warning that the installation steps may trigger a rebuild, but that it's not intended to rebuild every installation.
